version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - checkout
      - run:
          name: Install Maven
          command: |
            sudo apt-get update
            sudo apt-get install -y maven
      - run:
          name: Verify Maven Version
          command: mvn -v
      - run:
          name: Build and Test from Backend
          command: |
            cd Backend
            mvn clean verify

workflows:
  build_and_test:
    jobs:
      - build
