version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Install Maven
          command: |
            sudo apt-get update
            sudo apt-get install -y maven
      - run:
          name: Build and Run Unit Tests
          command: mvn clean verify

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
