version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0-maven
    steps:
      - checkout
      - run:
          name: Build and Test with Maven
          command: mvn clean verify

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
